//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TDOMINIOS
{
    public int domi_consecutivo { get; set; }
    public string domi_nombre { get; set; }
    public int domi_estado { get; set; }
    public Nullable<System.DateTime> domi_fecha { get; set; }
    public string domi_grupo { get; set; }
}
