//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TSERVIDORES
{
    public GE_TSERVIDORES()
    {
        this.GE_TDISTRIBUCIONDEDICACIONPERSONA = new HashSet<GE_TDISTRIBUCIONDEDICACIONPERSONA>();
        this.GE_TDISTRIBUCIONINFRAESTRUCTURA = new HashSet<GE_TDISTRIBUCIONINFRAESTRUCTURA>();
    }

    public int serv_consecutivo { get; set; }
    public string serv_nombre { get; set; }
    public string ser_marca { get; set; }
    public string ser_modelo { get; set; }
    public string serv_funcion { get; set; }
    public string serv_estado { get; set; }
    public string serv_ip { get; set; }
    public string ser_sistema_operativo { get; set; }
    public string serv_numero_bits { get; set; }
    public Nullable<decimal> serv_memoria { get; set; }
    public string serv_procesadores { get; set; }
    public Nullable<decimal> serv_core { get; set; }
    public Nullable<decimal> serv_disco_duro { get; set; }
    public string serv_descripcion_disco_duro { get; set; }
    public string serv_aplicaciones_instaladas { get; set; }
    public Nullable<int> serv_virtualizado { get; set; }
    public string serv_software_virtualizacion { get; set; }
    public string serv_granja_virtual { get; set; }
    public string serv_ubicacion_fisica { get; set; }
    public string serv_activo_fijo { get; set; }
    public Nullable<int> serv_depreciable { get; set; }
    public int serv_activo { get; set; }
    public string serv_estadoStr { get; set; }
    public string serv_usuario { get; set; }
    public System.DateTime serv_fecha { get; set; }

    public virtual ICollection<GE_TDISTRIBUCIONDEDICACIONPERSONA> GE_TDISTRIBUCIONDEDICACIONPERSONA { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONINFRAESTRUCTURA> GE_TDISTRIBUCIONINFRAESTRUCTURA { get; set; }
}
