//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TVLR_CUADRO_SERVICIO_DETALLE
{
    public int Consecutivo { get; set; }
    public Nullable<int> Idservicio { get; set; }
    public string Servicio { get; set; }
    public Nullable<int> IdProducto { get; set; }
    public string Producto { get; set; }
    public string Tipo { get; set; }
    public string SubTipo { get; set; }
    public string ServPersona { get; set; }
    public string Item { get; set; }
    public Nullable<decimal> Valor { get; set; }
    public string Usuario { get; set; }
    public Nullable<System.DateTime> Fecha { get; set; }
}
