//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCARGUEDISTRIBUCION
{
    public int cadi_consecutivo { get; set; }
    public Nullable<int> cadi_co_origen { get; set; }
    public Nullable<int> cadi_co_destino { get; set; }
    public Nullable<decimal> cadi_porcentaje { get; set; }
    public string cadi_usuario { get; set; }
    public Nullable<System.DateTime> cadi_fecha { get; set; }
    public string cadi_usuario_act { get; set; }
    public Nullable<System.DateTime> cadi_fecha_act { get; set; }
    public Nullable<int> cadi_activo { get; set; }

    public virtual GE_TCENTROSOPERACION GE_TCENTROSOPERACION { get; set; }
    public virtual GE_TCENTROSOPERACION GE_TCENTROSOPERACION1 { get; set; }
}
