//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCLASESPARAMETROS
{
    public GE_TCLASESPARAMETROS()
    {
        this.GE_TPARAMETROS = new HashSet<GE_TPARAMETROS>();
    }

    public int clap_clase { get; set; }
    public string clap_nombre { get; set; }
    public string clap_descripcion { get; set; }
    public System.DateTime clap_fechaini { get; set; }
    public Nullable<System.DateTime> clap_fechafin { get; set; }
    public int clap_estado { get; set; }

    public string clap_estadoStr { get; set; }

    public virtual ICollection<GE_TPARAMETROS> GE_TPARAMETROS { get; set; }
}
