//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TREDISTRIBUCION_DRIVERS
{
    public int care_consecutivo { get; set; }
    public Nullable<int> care_ceop_id { get; set; }
    public Nullable<int> care_cargue_driver { get; set; }
    public Nullable<decimal> care_valor { get; set; }
    public string care_usuario { get; set; }
    public Nullable<System.DateTime> care_fecha { get; set; }
    public string care_usuario_act { get; set; }
    public Nullable<System.DateTime> care_fecha_act { get; set; }
    public string care_activo { get; set; }

    public virtual GE_TCARGUEDRIVERS GE_TCARGUEDRIVERS { get; set; }
    public virtual GE_TCENTROSOPERACION GE_TCENTROSOPERACION { get; set; }
}
