//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCUENTASCLASIFICACION
{
    public int cucl_consecutivo { get; set; }
    public int cucl_cuenta { get; set; }
    public int cucl_ccosto { get; set; }
    public int cucl_subcategoria { get; set; }
    public int cucl_tipo { get; set; }
    public string cucl_usuario { get; set; }
    public System.DateTime cucl_fecha { get; set; }

    public virtual GE_TCUENTAS GE_TCUENTAS { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS1 { get; set; }
    public virtual GE_TCENTROSCOSTOS GE_TCENTROSCOSTOS { get; set; }
}
