//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TUSUARIOS_ACCESOS
{
    public int usac_consecutivo { get; set; }
    public string usua_usuario { get; set; }
    public System.DateTime usac_fecha_ingreso { get; set; }
    public Nullable<System.DateTime> usac_fecha_salida { get; set; }
    public int usac_estado { get; set; }
    public string usac_tipo_salida { get; set; }
    public string usac_hostname { get; set; }
    public string usac_ip { get; set; }
    public string usac_browser { get; set; }
    public string usac_usuario_desbloqueo { get; set; }
    public string usac_guid { get; set; }
    public string usac_ipantesproxy { get; set; }
}
