//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCUENTAS
{
    public GE_TCUENTAS()
    {
        this.GE_TCUENTASCLASIFICACION = new HashSet<GE_TCUENTASCLASIFICACION>();
        this.GE_TPRODUCTOSITEMS = new HashSet<GE_TPRODUCTOSITEMS>();
    }

    public int cuen_consecutivo { get; set; }
    public string cuen_auxiliar { get; set; }
    public string cuen_descripcion { get; set; }
    public string cuen_mayor { get; set; }
    public int cuen_activo { get; set; }
    public string cuen_usuario { get; set; }
    public System.DateTime cuen_fecha { get; set; }
    public Nullable<int> cuen_amortizar { get; set; }

    public virtual ICollection<GE_TCUENTASCLASIFICACION> GE_TCUENTASCLASIFICACION { get; set; }
    public virtual ICollection<GE_TPRODUCTOSITEMS> GE_TPRODUCTOSITEMS { get; set; }
}
