//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TOPCIONESMENUXROL
{
    public int opcr_consecutivo { get; set; }
    public int rolm_consecutivo { get; set; }
    public int opcm_consecutivo { get; set; }
    public Nullable<System.DateTime> opcr_fecha { get; set; }
    public string opcr_usuario { get; set; }

    public virtual GE_TOPCIONESMENU GE_TOPCIONESMENU { get; set; }
    public virtual GE_TROLES GE_TROLES { get; set; }
}
