//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TOPCIONESMENU
{
    public GE_TOPCIONESMENU()
    {
        this.GE_TOPCIONESMENUXROL = new HashSet<GE_TOPCIONESMENUXROL>();
    }

    public int opcm_consecutivo { get; set; }
    public int opcm_idpadre { get; set; }
    public int opcm_idonma { get; set; }
    public int opcm_idpadreonma { get; set; }
    public int opcm_idobjetoonma { get; set; }
    public string opcm_titulo { get; set; }
    public string opcm_descripcion { get; set; }
    public string opcm_url { get; set; }
    public string opcm_ruta_imagen { get; set; }
    public int opcm_estado { get; set; }
    public System.DateTime opcm_fecha { get; set; }
    public System.DateTime opcm_fecha_act { get; set; }
    public string opcm_tipo { get; set; }
    public string opcm_usuario { get; set; }
    public string opcm_usuario_act { get; set; }

    public virtual ICollection<GE_TOPCIONESMENUXROL> GE_TOPCIONESMENUXROL { get; set; }
}
