//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPARAMETROS
{
    public GE_TPARAMETROS()
    {
        this.GE_TCALCULOGASTOSVIAJE = new HashSet<GE_TCALCULOGASTOSVIAJE>();
        this.GE_TCALCULOGASTOSVIAJE1 = new HashSet<GE_TCALCULOGASTOSVIAJE>();
        this.GE_TCUENTASCLASIFICACION = new HashSet<GE_TCUENTASCLASIFICACION>();
        this.GE_TCUENTASCLASIFICACION1 = new HashSet<GE_TCUENTASCLASIFICACION>();
        this.GE_TDELEGADOS = new HashSet<GE_TDELEGADOS>();
        this.GE_TPERIODOTRANSACCIONES = new HashSet<GE_TPERIODOTRANSACCIONES>();
        this.GE_TPERIODOTRANSACCIONES1 = new HashSet<GE_TPERIODOTRANSACCIONES>();
        this.GE_TPRODUCTOS = new HashSet<GE_TPRODUCTOS>();
        this.GE_TPRODUCTOS1 = new HashSet<GE_TPRODUCTOS>();
        this.GE_TPRODUCTOS2 = new HashSet<GE_TPRODUCTOS>();
        this.GE_TPRODUCTOS3 = new HashSet<GE_TPRODUCTOS>();
        this.GE_TPRODUCTOS4 = new HashSet<GE_TPRODUCTOS>();
        this.GE_TPRODUCTOS5 = new HashSet<GE_TPRODUCTOS>();
        this.GE_TPRODUCTOS6 = new HashSet<GE_TPRODUCTOS>();
        this.GE_TVARECONOMICAS = new HashSet<GE_TVARECONOMICAS>();
        this.GE_TVARECONOMICAS1 = new HashSet<GE_TVARECONOMICAS>();
        this.PARAMETROSGRALES = new HashSet<PARAMETROSGRALES>();
        this.PARAMETROSGRALES1 = new HashSet<PARAMETROSGRALES>();
        this.GE_TUSUARIOS = new HashSet<GE_TUSUARIOS>();
        this.GE_TCENTROSCOSTOS = new HashSet<GE_TCENTROSCOSTOS>();
        this.GE_TCENTROSCOSTOS1 = new HashSet<GE_TCENTROSCOSTOS>();
        this.GE_TCENTROSCOSTOS2 = new HashSet<GE_TCENTROSCOSTOS>();
        this.GE_TPERSONAS = new HashSet<GE_TPERSONAS>();
        this.GE_TPERSONAS1 = new HashSet<GE_TPERSONAS>();
        this.GE_TPERSONAS2 = new HashSet<GE_TPERSONAS>();
        this.GE_TPERSONAS3 = new HashSet<GE_TPERSONAS>();
        this.GE_TPERSONAS4 = new HashSet<GE_TPERSONAS>();
        this.GE_TPERSONAS5 = new HashSet<GE_TPERSONAS>();
        this.GE_TROLES = new HashSet<GE_TROLES>();
    }

    public int parm_consecutivo { get; set; }
    public int clap_clase { get; set; }
    public string parm_descripcion { get; set; }
    public System.DateTime parm_fechadesde { get; set; }
    public Nullable<System.DateTime> parm_fechahasta { get; set; }
    public int parm_estado { get; set; }
    public string parm_estadoStr{ get; set; }
    public string parm_infoadicional { get; set; }
    public string parm_codigo { get; set; }

    public virtual ICollection<GE_TCALCULOGASTOSVIAJE> GE_TCALCULOGASTOSVIAJE { get; set; }
    public virtual ICollection<GE_TCALCULOGASTOSVIAJE> GE_TCALCULOGASTOSVIAJE1 { get; set; }
    public virtual GE_TCLASESPARAMETROS GE_TCLASESPARAMETROS { get; set; }
    public virtual ICollection<GE_TCUENTASCLASIFICACION> GE_TCUENTASCLASIFICACION { get; set; }
    public virtual ICollection<GE_TCUENTASCLASIFICACION> GE_TCUENTASCLASIFICACION1 { get; set; }
    public virtual ICollection<GE_TDELEGADOS> GE_TDELEGADOS { get; set; }
    public virtual ICollection<GE_TPERIODOTRANSACCIONES> GE_TPERIODOTRANSACCIONES { get; set; }
    public virtual ICollection<GE_TPERIODOTRANSACCIONES> GE_TPERIODOTRANSACCIONES1 { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS1 { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS2 { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS3 { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS4 { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS5 { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS6 { get; set; }
    public virtual ICollection<GE_TVARECONOMICAS> GE_TVARECONOMICAS { get; set; }
    public virtual ICollection<GE_TVARECONOMICAS> GE_TVARECONOMICAS1 { get; set; }
    public virtual ICollection<PARAMETROSGRALES> PARAMETROSGRALES { get; set; }
    public virtual ICollection<PARAMETROSGRALES> PARAMETROSGRALES1 { get; set; }
    public virtual ICollection<GE_TUSUARIOS> GE_TUSUARIOS { get; set; }
    public virtual ICollection<GE_TCENTROSCOSTOS> GE_TCENTROSCOSTOS { get; set; }
    public virtual ICollection<GE_TCENTROSCOSTOS> GE_TCENTROSCOSTOS1 { get; set; }
    public virtual ICollection<GE_TCENTROSCOSTOS> GE_TCENTROSCOSTOS2 { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS1 { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS2 { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS3 { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS4 { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS5 { get; set; }
    public virtual ICollection<GE_TROLES> GE_TROLES { get; set; }
}
