//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_THISTORICOPYG
{
    public GE_THISTORICOPYG()
    {
        this.GE_TPORCENTAJESPYG = new HashSet<GE_TPORCENTAJESPYG>();
    }

    public int vent_consecutivo { get; set; }
    public Nullable<int> vent_periodo { get; set; }
    public Nullable<int> vent_ceop { get; set; }
    public Nullable<decimal> vent_valor_ventas { get; set; }
    public Nullable<decimal> vent_valor_directos { get; set; }
    public Nullable<decimal> vent_valor_indirectos { get; set; }
    public string vent_tipo { get; set; }
    public string vent_usuario { get; set; }
    public Nullable<System.DateTime> vent_fecha { get; set; }
    public string vent_usuario_act { get; set; }
    public Nullable<System.DateTime> vent_fecha_act { get; set; }
    public Nullable<int> vent_activo { get; set; }

    public virtual GE_TCENTROSOPERACION GE_TCENTROSOPERACION { get; set; }
    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual ICollection<GE_TPORCENTAJESPYG> GE_TPORCENTAJESPYG { get; set; }
}
