//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TDISTRIBUCIONMASPROCESOS
{
    public int dmas_consecutivo { get; set; }
    public int dmas_periodo { get; set; }
    public int dmas_producto { get; set; }
    public decimal dmas_valor { get; set; }
    public string dmas_usuario { get; set; }
    public System.DateTime dmas_fecha { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
}
