//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TUSUARIOSXROL
{
    public int usxr_consecutivo { get; set; }
    public int rolm_consecutivo { get; set; }
    public int usua_usuario { get; set; }
    public int usxr_estado { get; set; }
    public System.DateTime usxr_fecha { get; set; }
    public System.DateTime usxr_fecha_act { get; set; }
    public string usxr_usuario { get; set; }
    public string usxr_usuario_act { get; set; }

    public virtual GE_TUSUARIOS GE_TUSUARIOS { get; set; }
    public virtual GE_TROLES GE_TROLES { get; set; }
}
