//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCARGUEDRIVERS
{
    public GE_TCARGUEDRIVERS()
    {
        this.GE_TREDISTRIBUCION_DRIVERS = new HashSet<GE_TREDISTRIBUCION_DRIVERS>();
    }

    public int carg_consecutivo { get; set; }
    public Nullable<int> carg_periodo { get; set; }
    public Nullable<int> carg_producto { get; set; }
    public Nullable<int> carg_compania { get; set; }
    public string carg_sede { get; set; }
    public Nullable<int> carg_ccosto { get; set; }
    public Nullable<int> carg_driver { get; set; }
    public Nullable<decimal> carg_cantidad { get; set; }
    public Nullable<int> carg_valor { get; set; }
    public Nullable<decimal> carg_valor_distribucion { get; set; }
    public Nullable<decimal> carg_valor_adicional { get; set; }
    public Nullable<decimal> carg_valor_total { get; set; }
    public string carg_proveedor { get; set; }
    public string carg_usuario { get; set; }
    public Nullable<System.DateTime> carg_fecha { get; set; }
    public string carg_usuario_act { get; set; }
    public Nullable<System.DateTime> carg_fecha_act { get; set; }
    public Nullable<int> carg_activo { get; set; }

    public virtual GE_TDRIVERS GE_TDRIVERS { get; set; }
    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual ICollection<GE_TREDISTRIBUCION_DRIVERS> GE_TREDISTRIBUCION_DRIVERS { get; set; }
    public virtual GE_TCENTROSCOSTOS GE_TCENTROSCOSTOS { get; set; }
    public virtual GE_TCOMPANIAS GE_TCOMPANIAS { get; set; }
}
