//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TSALIDAPRESUPUESTO
{
    public int sali_consecutivo { get; set; }
    public int sali_periodo_transacc { get; set; }
    public int sali_persona { get; set; }
    public int sali_centrocosto { get; set; }
    public int sali_producto_item { get; set; }
    public int sali_mes { get; set; }
    public int sali_moneda { get; set; }
    public decimal sali_valor { get; set; }
    public string sali_usuario { get; set; }
    public System.DateTime sali_fecha { get; set; }
    public string sali_tipo { get; set; }
    public Nullable<int> sali_periodo { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOSITEMS GE_TPRODUCTOSITEMS { get; set; }
    public virtual GE_TCENTROSCOSTOS GE_TCENTROSCOSTOS { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS { get; set; }
}
