//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TVARECONOMICAS
{
    public int vari_consecutivo { get; set; }
    public int vari_tipo_moneda { get; set; }
    public int vari_ano { get; set; }
    public int vari_mes { get; set; }
    public decimal vari_valor { get; set; }
    public int vari_activo { get; set; }
    public string vari_usuario { get; set; }
    public System.DateTime vari_fecha { get; set; }

    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS1 { get; set; }
}
