//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPERIODOTRANSACCPERSONAS
{
    public int ptrp_consecutivo { get; set; }
    public int ptrp_periodo_transacc { get; set; }
    public int ptrp_persona { get; set; }
    public int ptrp_cantidad_dias { get; set; }
    public decimal ptrp_tarifa_hotel { get; set; }
    public decimal ptrp_tarifa_alimentacion { get; set; }
    public int ptrp_mes { get; set; }
    public decimal ptrp_smmlv { get; set; }
    public string ptrp_usuario { get; set; }
    public System.DateTime ptrp_fecha { get; set; }

    public virtual GE_TPERIODOTRANSACCIONES GE_TPERIODOTRANSACCIONES { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS { get; set; }
}
