//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPERIODOPRESUPUESTO
{
    public GE_TPERIODOPRESUPUESTO()
    {
        this.GE_TCARGUEARCHIVOS = new HashSet<GE_TCARGUEARCHIVOS>();
        this.GE_TCARGUEDRIVERS = new HashSet<GE_TCARGUEDRIVERS>();
        this.GE_TDISTRIBUCIONCARGUEGA = new HashSet<GE_TDISTRIBUCIONCARGUEGA>();
        this.GE_TDISTRIBUCIONDEDICACIONPERSONA = new HashSet<GE_TDISTRIBUCIONDEDICACIONPERSONA>();
        this.GE_TDISTRIBUCIONINFRAESTRUCTURA = new HashSet<GE_TDISTRIBUCIONINFRAESTRUCTURA>();
        this.GE_TDISTRIBUCIONINTERMEDIOS = new HashSet<GE_TDISTRIBUCIONINTERMEDIOS>();
        this.GE_TDISTRIBUCIONMASPROCESOS = new HashSet<GE_TDISTRIBUCIONMASPROCESOS>();
        this.GE_THISTORICOPYG = new HashSet<GE_THISTORICOPYG>();
        this.GE_TPERIODOTRANSACCIONES = new HashSet<GE_TPERIODOTRANSACCIONES>();
        this.GE_TREDISTRIBUCION = new HashSet<GE_TREDISTRIBUCION>();
        this.GE_TRELITEMSDATACENTERPROD = new HashSet<GE_TRELITEMSDATACENTERPROD>();
        this.GE_TSALIDAPRESUPUESTO = new HashSet<GE_TSALIDAPRESUPUESTO>();
        this.GE_TGENTE = new HashSet<GE_TGENTE>();
        this.GE_TCARGUEARCHIVOSLABORAL = new HashSet<GE_TCARGUEARCHIVOSLABORAL>();
    }

    public int peri_consecutivo { get; set; }
    public int peri_ano { get; set; }
    public int peri_paso { get; set; }
    public int peri_activo { get; set; }
    public string peri_estadoStr {set;get;}
    public string peri_usuario { get; set; }
    public System.DateTime peri_fecha { get; set; }

    public virtual ICollection<GE_TCARGUEARCHIVOS> GE_TCARGUEARCHIVOS { get; set; }
    public virtual ICollection<GE_TCARGUEDRIVERS> GE_TCARGUEDRIVERS { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONCARGUEGA> GE_TDISTRIBUCIONCARGUEGA { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONDEDICACIONPERSONA> GE_TDISTRIBUCIONDEDICACIONPERSONA { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONINFRAESTRUCTURA> GE_TDISTRIBUCIONINFRAESTRUCTURA { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONINTERMEDIOS> GE_TDISTRIBUCIONINTERMEDIOS { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONMASPROCESOS> GE_TDISTRIBUCIONMASPROCESOS { get; set; }
    public virtual ICollection<GE_THISTORICOPYG> GE_THISTORICOPYG { get; set; }
    public virtual ICollection<GE_TPERIODOTRANSACCIONES> GE_TPERIODOTRANSACCIONES { get; set; }
    public virtual ICollection<GE_TREDISTRIBUCION> GE_TREDISTRIBUCION { get; set; }
    public virtual ICollection<GE_TRELITEMSDATACENTERPROD> GE_TRELITEMSDATACENTERPROD { get; set; }
    public virtual ICollection<GE_TSALIDAPRESUPUESTO> GE_TSALIDAPRESUPUESTO { get; set; }
    public virtual ICollection<GE_TGENTE> GE_TGENTE { get; set; }
    public virtual ICollection<GE_TCARGUEARCHIVOSLABORAL> GE_TCARGUEARCHIVOSLABORAL { get; set; }
}
