//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TVLR_CUADRO_SERVICIO
{
    public int cuad_consecutivo { get; set; }
    public Nullable<int> idprod { get; set; }
    public string producto { get; set; }
    public string item { get; set; }
    public Nullable<decimal> vlr_lic { get; set; }
    public Nullable<decimal> vlr_int_lic { get; set; }
    public Nullable<decimal> vlr_infr { get; set; }
    public Nullable<decimal> vlr_datac { get; set; }
    public Nullable<decimal> vlr_mas_ga { get; set; }
    public Nullable<decimal> vlr_mas_softw { get; set; }
    public Nullable<decimal> vlr_mas_infr { get; set; }
    public Nullable<decimal> vlr_mas_datac { get; set; }
    public Nullable<decimal> vlr_mas_gente { get; set; }
    public Nullable<decimal> vlr_ga_operaciones { get; set; }
    public Nullable<decimal> vlr_ga_gtecnica { get; set; }
    public Nullable<decimal> vlr_ga_desarrollo { get; set; }
    public Nullable<decimal> vlr_mas_cdm { get; set; }
    public Nullable<decimal> vlr_mas_procesos { get; set; }
    public Nullable<decimal> total { get; set; }
}
