//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCENTROSOPERACION
{
    public GE_TCENTROSOPERACION()
    {
        this.GE_TCARGUEDISTRIBUCION = new HashSet<GE_TCARGUEDISTRIBUCION>();
        this.GE_TCARGUEDISTRIBUCION1 = new HashSet<GE_TCARGUEDISTRIBUCION>();
        this.GE_THISTORICOPYG = new HashSet<GE_THISTORICOPYG>();
        this.GE_TREDISTRIBUCION_DRIVERS = new HashSet<GE_TREDISTRIBUCION_DRIVERS>();
        this.GE_TGENTE = new HashSet<GE_TGENTE>();
        this.GE_TPERSONAS = new HashSet<GE_TPERSONAS>();
    }

    public int ceop_consecutivo { get; set; }
    public string ceop_codigo { get; set; }
    public string ceop_descripcion { get; set; }
    public int ceop_activo { get; set; }
    public string ceop_estadoStr { get; set; }
    public string ceop_usuario { get; set; }
    public System.DateTime ceop_fecha { get; set; }
    public string ceop_vicepresidencia { get; set; }

    public virtual ICollection<GE_TCARGUEDISTRIBUCION> GE_TCARGUEDISTRIBUCION { get; set; }
    public virtual ICollection<GE_TCARGUEDISTRIBUCION> GE_TCARGUEDISTRIBUCION1 { get; set; }
    public virtual ICollection<GE_THISTORICOPYG> GE_THISTORICOPYG { get; set; }
    public virtual ICollection<GE_TREDISTRIBUCION_DRIVERS> GE_TREDISTRIBUCION_DRIVERS { get; set; }
    public virtual ICollection<GE_TGENTE> GE_TGENTE { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS { get; set; }
}
