//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TUSUARIOS
{
    public GE_TUSUARIOS()
    {
        this.GE_TUSUARIOSXROL = new HashSet<GE_TUSUARIOSXROL>();
    }

    public int USUA_USUARIO { get; set; }
    public string USUA_USERNAME { get; set; }
    public string USUA_CLAVE { get; set; }
    public string USUA_DOMINIO { get; set; }
    public Nullable<System.DateTime> USUA_FECHA { get; set; }
    public string USUA_HORA { get; set; }
    public int USUA_ESTADO { get; set; }
    public string USUA_ENCRIPTA { get; set; }
    public Nullable<System.DateTime> USUA_FECHAVENCE { get; set; }
    public Nullable<System.DateTime> USUA_FECHACAMBIO { get; set; }
    public Nullable<System.DateTime> USUA_FECHA_ACT { get; set; }
    public string USUA_USUARIO_INS { get; set; }
    public string USUA_USUARIO_ACT { get; set; }
    public Nullable<int> PARM_TIPOUSUARIO { get; set; }
    public string USUA_VALIDALDAP { get; set; }

    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual ICollection<GE_TUSUARIOSXROL> GE_TUSUARIOSXROL { get; set; }
}
