//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TDELEGADOS
{
    public int dele_consecutivo { get; set; }
    public int dele_jefe { get; set; }
    public int dele_delegado { get; set; }
    public string dele_usuario_crea { get; set; }
    public string dele_usuario_act { get; set; }
    public Nullable<System.DateTime> dele_fecha { get; set; }
    public Nullable<System.DateTime> dele_fecha_act { get; set; }
    public Nullable<int> dele_activo { get; set; }
    public Nullable<int> dele_fase_parm { get; set; }

    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS1 { get; set; }
}
