//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPRODUCTOS
{
    public GE_TPRODUCTOS()
    {
        this.GE_TCARGUEARCHIVOS = new HashSet<GE_TCARGUEARCHIVOS>();
        this.GE_TCARGUEDRIVERS = new HashSet<GE_TCARGUEDRIVERS>();
        this.GE_TDISTRIBUCIONCARGUEGA = new HashSet<GE_TDISTRIBUCIONCARGUEGA>();
        this.GE_TDISTRIBUCIONDEDICACIONPERSONA = new HashSet<GE_TDISTRIBUCIONDEDICACIONPERSONA>();
        this.GE_TDISTRIBUCIONINFRAESTRUCTURA = new HashSet<GE_TDISTRIBUCIONINFRAESTRUCTURA>();
        this.GE_TDISTRIBUCIONINTERMEDIOS = new HashSet<GE_TDISTRIBUCIONINTERMEDIOS>();
        this.GE_TDISTRIBUCIONINTERMEDIOS1 = new HashSet<GE_TDISTRIBUCIONINTERMEDIOS>();
        this.GE_TDISTRIBUCIONMASPROCESOS = new HashSet<GE_TDISTRIBUCIONMASPROCESOS>();
        this.GE_TFAMILIAS_PRODUCTOS = new HashSet<GE_TFAMILIAS_PRODUCTOS>();
        this.GE_TFAMILIAS_PRODUCTOS1 = new HashSet<GE_TFAMILIAS_PRODUCTOS>();
        this.GE_TPRODUCTOSITEMS = new HashSet<GE_TPRODUCTOSITEMS>();
        this.GE_TREDISTRIBUCION = new HashSet<GE_TREDISTRIBUCION>();
        this.GE_TREDISTRIBUCION1 = new HashSet<GE_TREDISTRIBUCION>();
        this.GE_TRELITEMSDATACENTERPROD = new HashSet<GE_TRELITEMSDATACENTERPROD>();
    }

    public int prod_consecutivo { get; set; }
    public string prod_codigo { get; set; }
    public string prod_descripcion { get; set; }
    public int prod_responsable { get; set; }
    public int prod_tipo_licencia { get; set; }
    public int prod_intermedio { get; set; }
    public int prod_contrato { get; set; }
    public int prod_componente { get; set; }
    public int prod_criterio { get; set; }
    public int prod_activo { get; set; }
    public string prod_usuario { get; set; }
    public System.DateTime prod_fecha { get; set; }
    public string prod_usuario_act { get; set; }
    public System.DateTime prod_fecha_act { get; set; }
    public Nullable<int> prod_serv_venta { get; set; }
    public Nullable<int> prod_driver1 { get; set; }
    public Nullable<int> prod_driver2 { get; set; }
    public Nullable<int> prod_categ_serv { get; set; }
    public Nullable<int> prod_tipo { get; set; }
    public Nullable<int> prod_redistribuir { get; set; }
    public Nullable<int> prod_interm_no_distrib { get; set; }
    public Nullable<int> prod_distrib_serv { get; set; }
    public Nullable<int> prod_tipo_producto { get; set; }
    public Nullable<int> prod_directo_agrupado { get; set; }

    public virtual ICollection<GE_TCARGUEARCHIVOS> GE_TCARGUEARCHIVOS { get; set; }
    public virtual ICollection<GE_TCARGUEDRIVERS> GE_TCARGUEDRIVERS { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONCARGUEGA> GE_TDISTRIBUCIONCARGUEGA { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONDEDICACIONPERSONA> GE_TDISTRIBUCIONDEDICACIONPERSONA { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONINFRAESTRUCTURA> GE_TDISTRIBUCIONINFRAESTRUCTURA { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONINTERMEDIOS> GE_TDISTRIBUCIONINTERMEDIOS { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONINTERMEDIOS> GE_TDISTRIBUCIONINTERMEDIOS1 { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONMASPROCESOS> GE_TDISTRIBUCIONMASPROCESOS { get; set; }
    public virtual GE_TDRIVERS GE_TDRIVERS { get; set; }
    public virtual GE_TDRIVERS GE_TDRIVERS1 { get; set; }
    public virtual ICollection<GE_TFAMILIAS_PRODUCTOS> GE_TFAMILIAS_PRODUCTOS { get; set; }
    public virtual ICollection<GE_TFAMILIAS_PRODUCTOS> GE_TFAMILIAS_PRODUCTOS1 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS1 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS2 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS3 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS4 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS5 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS6 { get; set; }
    public virtual ICollection<GE_TPRODUCTOSITEMS> GE_TPRODUCTOSITEMS { get; set; }
    public virtual ICollection<GE_TREDISTRIBUCION> GE_TREDISTRIBUCION { get; set; }
    public virtual ICollection<GE_TREDISTRIBUCION> GE_TREDISTRIBUCION1 { get; set; }
    public virtual ICollection<GE_TRELITEMSDATACENTERPROD> GE_TRELITEMSDATACENTERPROD { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS { get; set; }
}
