//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCALCULOGASTOSVIAJE
{
    public int tari_consecutivo { get; set; }
    public int tari_grupo { get; set; }
    public int tari_destino { get; set; }
    public decimal tari_hotel { get; set; }
    public decimal tari_alimentacion { get; set; }
    public int tari_estado { get; set; }
    public string tari_usuario { get; set; }
    public System.DateTime tari_fecha { get; set; }

    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS1 { get; set; }
}
