//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCARGUEARCHIVOS
{
    public int carg_consecutivo { get; set; }
    public int carg_producto { get; set; }
    public int carg_periodo { get; set; }
    public string carg_empresa { get; set; }
    public string carg_ccosto { get; set; }
    public string carg_user { get; set; }
    public string carg_item { get; set; }
    public string carg_equipo { get; set; }
    public string carg_leasing { get; set; }
    public string carg_papel { get; set; }
    public string carg_mes { get; set; }
    public string carg_proveedor { get; set; }
    public string carg_cantidad { get; set; }
    public Nullable<decimal> carg_valor { get; set; }
    public string carg_observacion { get; set; }
    public string carg_usuario { get; set; }
    public Nullable<System.DateTime> carg_fecha { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
}
