//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TDISTRIBUCIONCARGUEGA
{
    public int card_consecutivo { get; set; }
    public int card_periodo { get; set; }
    public int card_producto { get; set; }
    public int card_ccosto { get; set; }
    public decimal card_valor { get; set; }
    public string card_usuario { get; set; }
    public System.DateTime card_fecha { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual GE_TCENTROSCOSTOS GE_TCENTROSCOSTOS { get; set; }
}
