//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPERSONAS
{
    public GE_TPERSONAS()
    {
        this.GE_TCENTROSCOSTOS = new HashSet<GE_TCENTROSCOSTOS>();
        this.GE_TCENTROSCOSTOS1 = new HashSet<GE_TCENTROSCOSTOS>();
        this.GE_TDELEGADOS = new HashSet<GE_TDELEGADOS>();
        this.GE_TDELEGADOS1 = new HashSet<GE_TDELEGADOS>();
        this.GE_TDISTRIBUCIONDEDICACIONPERSONA = new HashSet<GE_TDISTRIBUCIONDEDICACIONPERSONA>();
        this.GE_TGENTE = new HashSet<GE_TGENTE>();
        this.GE_TPERIODOTRANSACCIONES = new HashSet<GE_TPERIODOTRANSACCIONES>();
        this.GE_TPERIODOTRANSACCPERSONAS = new HashSet<GE_TPERIODOTRANSACCPERSONAS>();
        this.GE_TPERSONAS1 = new HashSet<GE_TPERSONAS>();
        this.GE_TPRODUCTOS = new HashSet<GE_TPRODUCTOS>();
        this.GE_TSALIDAPRESUPUESTO = new HashSet<GE_TSALIDAPRESUPUESTO>();
    }

    public int pers_consecutivo { get; set; }
    public string pers_tipodoc { get; set; }
    public string pers_identificacion { get; set; }
    public string pers_nombre { get; set; }
    public string pers_apellido { get; set; }
    public string pers_nombres { get; set; }
    public int pers_consec_jefe { get; set; }
    public int pers_tipo_contrato { get; set; }
    public int pers_metodo_distrib { get; set; }
    public int pers_cargo { get; set; }
    public int pers_grupo { get; set; }
    public int pers_activo { get; set; }
    public string pers_estadoStr { get; set; }
    public Nullable<int> pers_empresa { get; set; }
    public Nullable<int> pers_ccosto { get; set; }
    public string pers_usudom { get; set; }
    public Nullable<int> pers_nombre_area { get; set; }
    public string pers_nombre_busq { get; set; }
    public Nullable<int> pers_ceop { get; set; }
    public string pers_usuario { get; set; }
    public string pers_usuario_act { get; set; }
    public System.DateTime pers_fecha_act { get; set; }
    public System.DateTime pers_fecha { get; set; }

    public virtual ICollection<GE_TCENTROSCOSTOS> GE_TCENTROSCOSTOS { get; set; }
    public virtual ICollection<GE_TCENTROSCOSTOS> GE_TCENTROSCOSTOS1 { get; set; }
    public virtual GE_TCENTROSCOSTOS GE_TCENTROSCOSTOS2 { get; set; }
    public virtual GE_TCENTROSOPERACION GE_TCENTROSOPERACION { get; set; }
    public virtual ICollection<GE_TDELEGADOS> GE_TDELEGADOS { get; set; }
    public virtual ICollection<GE_TDELEGADOS> GE_TDELEGADOS1 { get; set; }
    public virtual ICollection<GE_TDISTRIBUCIONDEDICACIONPERSONA> GE_TDISTRIBUCIONDEDICACIONPERSONA { get; set; }
    public virtual ICollection<GE_TGENTE> GE_TGENTE { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS1 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS2 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS3 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS4 { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS5 { get; set; }
    public virtual ICollection<GE_TPERIODOTRANSACCIONES> GE_TPERIODOTRANSACCIONES { get; set; }
    public virtual ICollection<GE_TPERIODOTRANSACCPERSONAS> GE_TPERIODOTRANSACCPERSONAS { get; set; }
    public virtual ICollection<GE_TPERSONAS> GE_TPERSONAS1 { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS2 { get; set; }
    public virtual ICollection<GE_TPRODUCTOS> GE_TPRODUCTOS { get; set; }
    public virtual ICollection<GE_TSALIDAPRESUPUESTO> GE_TSALIDAPRESUPUESTO { get; set; }
}
