//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TDISTRIBUCIONDEDICACIONPERSONA
{
    public int dper_consecutivo { get; set; }
    public int dper_periodo { get; set; }
    public string dper_tipo { get; set; }
    public int dper_persona { get; set; }
    public Nullable<int> dper_servidor { get; set; }
    public Nullable<int> dper_producto { get; set; }
    public decimal dper_valor { get; set; }
    public int dper_estado { get; set; }
    public string dper_usuario { get; set; }
    public System.DateTime dper_fecha { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual GE_TSERVIDORES GE_TSERVIDORES { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS { get; set; }
}
