//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPORCENTAJESPYG
{
    public int hipo_consecutivo { get; set; }
    public Nullable<int> hipo_historico_id { get; set; }
    public Nullable<decimal> hipo_gastos_totales { get; set; }
    public Nullable<decimal> hipo_porc_ventas { get; set; }
    public Nullable<decimal> hipo_porc_directos { get; set; }
    public Nullable<decimal> hipo_porc_indirectos { get; set; }
    public Nullable<decimal> hipo_porc_total { get; set; }
    public Nullable<decimal> hipo_gastos_fore_totales { get; set; }
    public Nullable<decimal> hipo_porc_fore_ventas { get; set; }
    public Nullable<decimal> hipo_porc_fore_directos { get; set; }
    public Nullable<decimal> hipo_porc_fore_indirectos { get; set; }
    public Nullable<decimal> hipo_porc_fore_total { get; set; }
    public string hipo_usuario { get; set; }
    public Nullable<System.DateTime> hipo_fecha { get; set; }
    public string hipo_usuario_act { get; set; }
    public Nullable<System.DateTime> hipo_fecha_act { get; set; }
    public Nullable<int> hipo_activo { get; set; }

    public virtual GE_THISTORICOPYG GE_THISTORICOPYG { get; set; }
}
