//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TDISTRIBUCIONINFRAESTRUCTURA
{
    public int dinf_consecutivo { get; set; }
    public int dinf_periodo { get; set; }
    public string dinf_tipo { get; set; }
    public int dinf_producto { get; set; }
    public Nullable<int> dinf_producto_item { get; set; }
    public int dinf_servidor { get; set; }
    public decimal dinf_valor { get; set; }
    public int dinf_estado { get; set; }
    public string dinf_usuario { get; set; }
    public System.DateTime dinf_fecha { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual GE_TPRODUCTOSITEMS GE_TPRODUCTOSITEMS { get; set; }
    public virtual GE_TSERVIDORES GE_TSERVIDORES { get; set; }
}
