//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TRELITEMSDATACENTERPROD
{
    public int drel_consecutivo { get; set; }
    public int drel_periodo { get; set; }
    public int drel_item_datacenter { get; set; }
    public int drel_producto { get; set; }
    public int drel_activo { get; set; }
    public string drel_usuario { get; set; }
    public System.DateTime drel_fecha { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual GE_TPRODUCTOSITEMS GE_TPRODUCTOSITEMS { get; set; }
}
