//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TDISTRIBUCIONINTERMEDIOS
{
    public int dint_consecutivo { get; set; }
    public int dint_periodo { get; set; }
    public int dint_producto_intermedio { get; set; }
    public int dint_item_intermedio { get; set; }
    public int dint_producto_directo { get; set; }
    public decimal dint_valor { get; set; }
    public int dint_estado { get; set; }
    public string dint_usuario { get; set; }
    public System.DateTime dint_fecha { get; set; }
    public Nullable<decimal> dint_valor_asignado { get; set; }
    public Nullable<decimal> dint_valor_item { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS1 { get; set; }
    public virtual GE_TPRODUCTOSITEMS GE_TPRODUCTOSITEMS { get; set; }
}
