//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TFACTURACIONCARGUEDRIVERS
{
    public int facd_consecutivo { get; set; }
    public int facd_periodo { get; set; }
    public int facd_producto { get; set; }
    public string facd_usuario_cargue { get; set; }
    public string facd_empresa { get; set; }
    public int facd_ceco { get; set; }
    public int facd_cebe { get; set; }
    public int facd_cantidad { get; set; }
    public string facd_usuario { get; set; }
    public System.DateTime facd_fecha { get; set; }

    public virtual GE_TCENTROSOPERACION GE_TCENTROSOPERACION { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TCENTROSCOSTOS GE_TCENTROSCOSTOS { get; set; }
}
