//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TCARGUEARCHIVOSLABORAL
{
    public int carl_consecutivo { get; set; }
    public int carl_periodo { get; set; }
    public string carl_categoria { get; set; }
    public string carl_subcategoria { get; set; }
    public string carl_ccostos { get; set; }
    public string carl_item { get; set; }
    public string carl_moneda { get; set; }
    public Nullable<int> carl_valor { get; set; }
    public Nullable<int> carl_cantidad { get; set; }
    public string carl_enero { get; set; }
    public string carl_febrero { get; set; }
    public string carl_marzo { get; set; }
    public string carl_abril { get; set; }
    public string carl_mayo { get; set; }
    public string carl_junio { get; set; }
    public string carl_julio { get; set; }
    public string carl_agosto { get; set; }
    public string carl_septiembre { get; set; }
    public string carl_octubre { get; set; }
    public string carl_noviembre { get; set; }
    public string carl_diciembre { get; set; }
    public string carl_usuario { get; set; }
    public Nullable<System.DateTime> carl_fecha { get; set; }
    public string carl_observaciones { get; set; }
    public string carl_producto { get; set; }
    public string carl_empresa { get; set; }

    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
}
