//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPROVEEDORES
{
    public GE_TPROVEEDORES()
    {
        this.GE_TPERIODOTRANSACCIONES = new HashSet<GE_TPERIODOTRANSACCIONES>();
    }

    public int prov_consecutivo { get; set; }
    public string prov_nombre { get; set; }
    public string prov_descripcion { get; set; }
    public int prov_activo { get; set; }
    public string prov_usuario { get; set; }
    public System.DateTime prov_fecha { get; set; }

    public virtual ICollection<GE_TPERIODOTRANSACCIONES> GE_TPERIODOTRANSACCIONES { get; set; }
}
