//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TFAMILIAS_PRODUCTOS
{
    public int fami_consecutivo { get; set; }
    public Nullable<int> fam_producto { get; set; }
    public Nullable<int> fam_padre { get; set; }
    public Nullable<System.DateTime> fam_fecha { get; set; }
    public string fam_usuario { get; set; }
    public Nullable<int> fam_estado { get; set; }

    public virtual GE_TPRODUCTOS GE_TPRODUCTOS { get; set; }
    public virtual GE_TPRODUCTOS GE_TPRODUCTOS1 { get; set; }
}
