//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GE_TPERIODOTRANSACCIONES
{
    public GE_TPERIODOTRANSACCIONES()
    {
        this.GE_TPERIODOTRANSACCPERSONAS = new HashSet<GE_TPERIODOTRANSACCPERSONAS>();
    }

    public int petr_consecutivo { get; set; }
    public int petr_periodo { get; set; }
    public int petr_persona { get; set; }
    public int petr_centrocosto { get; set; }
    public int petr_producto_item { get; set; }
    public int petr_moneda { get; set; }
    public decimal petr_valor { get; set; }
    public decimal petr_valor_amortizar { get; set; }
    public int petr_mes { get; set; }
    public int petr_proveedor { get; set; }
    public decimal petr_trm { get; set; }
    public int petr_cantidad { get; set; }
    public Nullable<int> petr_tipo_viaje { get; set; }
    public int petr_amortizar { get; set; }
    public string petr_observacion { get; set; }
    public int petr_activo { get; set; }
    public string petr_usuario { get; set; }
    public System.DateTime petr_fecha { get; set; }
    public string petr_usuario_act { get; set; }
    public System.DateTime petr_fecha_act { get; set; }
    public Nullable<int> petr_meses_amortizar { get; set; }
    public string petr_tipo { get; set; }

    public virtual GE_TPARAMETROS GE_TPARAMETROS { get; set; }
    public virtual GE_TPARAMETROS GE_TPARAMETROS1 { get; set; }
    public virtual GE_TPERIODOPRESUPUESTO GE_TPERIODOPRESUPUESTO { get; set; }
    public virtual GE_TPRODUCTOSITEMS GE_TPRODUCTOSITEMS { get; set; }
    public virtual GE_TPROVEEDORES GE_TPROVEEDORES { get; set; }
    public virtual ICollection<GE_TPERIODOTRANSACCPERSONAS> GE_TPERIODOTRANSACCPERSONAS { get; set; }
    public virtual GE_TCENTROSCOSTOS GE_TCENTROSCOSTOS { get; set; }
    public virtual GE_TPERSONAS GE_TPERSONAS { get; set; }
}
