//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VLRSPRMGRALES
{
    public int vhpg_consecutivo { get; set; }
    public string pmgr_parametro { get; set; }
    public System.DateTime vhpg_fecdesde { get; set; }
    public Nullable<System.DateTime> vhpg_fechasta { get; set; }
    public int vhpg_estado { get; set; }
    public string vhpg_valor { get; set; }
}
