//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_CUADRO_VENTAS_PYG
{
    public string ceop_codigo { get; set; }
    public Nullable<decimal> ventas { get; set; }
    public Nullable<decimal> indirectos { get; set; }
    public Nullable<decimal> directos { get; set; }
    public string tipo { get; set; }
    public Nullable<decimal> forecast_ventas { get; set; }
    public Nullable<decimal> forecast_indirectos { get; set; }
    public Nullable<decimal> forecast_directos { get; set; }
    public string forecast_tipo { get; set; }
}
