//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_CS_VLR_GA
{
    public int prod_consecutivo { get; set; }
    public string prod_codigo { get; set; }
    public string pers_nombre_area { get; set; }
    public string pers_nombres { get; set; }
    public Nullable<decimal> valor { get; set; }
}
