//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_CS_VLR_SERV_ITEM_INFRAESTRUCTURA
{
    public string serv_nombre { get; set; }
    public int dinf_servidor { get; set; }
    public string prod_codigo { get; set; }
    public int prod_consecutivo { get; set; }
    public decimal vlrprod { get; set; }
    public Nullable<decimal> vlserv { get; set; }
    public string prit_item { get; set; }
    public Nullable<decimal> vlritem { get; set; }
}
