//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_GENTE_TECNICA
{
    public string NUMERO_CEDULA { get; set; }
    public string NOMBRE { get; set; }
    public string TIPO_DISTRIBUCION { get; set; }
    public int IDSERVIDOR { get; set; }
    public string NOMBRE_SERVIDOR { get; set; }
    public int IDPRODUCTO { get; set; }
    public string NOMBRE_PRODUCTO { get; set; }
    public decimal PORCENTAJE_DEDICACION { get; set; }
    public Nullable<decimal> COSTO_COLABORADOR { get; set; }
    public Nullable<decimal> COSTO_DISTIBUCION { get; set; }
    public Nullable<decimal> TOTAL_PERSONA { get; set; }
    public int PERIODO_ACTUAL { get; set; }
}
