//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_PRESUPUESTO
{
    public Nullable<long> NFila { get; set; }
    public string identificacion { get; set; }
    public string nombre { get; set; }
    public string producto { get; set; }
    public string item { get; set; }
    public string cuenta { get; set; }
    public string ceco { get; set; }
    public int ano { get; set; }
    public int mes { get; set; }
    public string ano_mes { get; set; }
    public string moneda { get; set; }
    public decimal valor { get; set; }
    public string IDPROD { get; set; }
    public string IDIT { get; set; }
}
