//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_PRODUCTOS_DIRECTOS
{
    public int prod_consecutivo { get; set; }
    public string prod_codigo { get; set; }
    public int prod_responsable { get; set; }
    public Nullable<int> prod_driver1 { get; set; }
    public int prod_activo { get; set; }
    public string parm_descripcion { get; set; }
    public string servicio { get; set; }
    public Nullable<int> idservicio { get; set; }
}
