//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_SALIDA_PRESUPUESTO
{
    public int sali_consecutivo { get; set; }
    public string identificacion { get; set; }
    public string nombre { get; set; }
    public string producto { get; set; }
    public string item { get; set; }
    public string cuenta { get; set; }
    public string ceco { get; set; }
    public string mes { get; set; }
    public string descrip_mes { get; set; }
    public string ano_mes { get; set; }
    public string moneda { get; set; }
    public decimal valor { get; set; }
    public string sali_tipo { get; set; }
    public string pers_usudom { get; set; }
    public int iditem { get; set; }
    public int idprod { get; set; }
}
