//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_VLR_DISTRIB_MAS
{
    public int prod_consecutivo { get; set; }
    public string prod_codigo { get; set; }
    public decimal casos { get; set; }
    public Nullable<decimal> porc { get; set; }
    public Nullable<decimal> software { get; set; }
    public Nullable<decimal> infraestructura { get; set; }
    public Nullable<decimal> datacenter { get; set; }
    public Nullable<decimal> gente { get; set; }
    public Nullable<decimal> ga { get; set; }
    public int cdm { get; set; }
    public int procesos { get; set; }
    public Nullable<decimal> total { get; set; }
}
