//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_VLR_ITEMS_INFRAESTRUCTURA
{
    public int dinf_servidor { get; set; }
    public string serv_nombre { get; set; }
    public string prit_item { get; set; }
    public Nullable<decimal> valor_ind { get; set; }
    public Nullable<decimal> vlritem { get; set; }
    public Nullable<decimal> valor_total { get; set; }
    public Nullable<decimal> vlritem_serv { get; set; }
}
