//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_VLR_PROD_DATACENTER
{
    public int dinf_servidor { get; set; }
    public string serv_nombre { get; set; }
    public int dinf_producto { get; set; }
    public string prod_codigo { get; set; }
    public Nullable<decimal> vlrprd { get; set; }
}
