//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_VLR_CUADRO_SERVICIO_BPC
{
    public string SERVICIO { get; set; }
    public string PRODPC { get; set; }
    public string PRODUCTO { get; set; }
    public string TIPO { get; set; }
    public string SUBTIPO { get; set; }
    public string IDSERVICIO { get; set; }
    public string IDTIPO { get; set; }
    public string IDSUBTIPO { get; set; }
    public Nullable<decimal> VALOR { get; set; }
    public string LICENCIAS { get; set; }
    public string IDLICENCIAS { get; set; }
    public string INTERMEDIOS { get; set; }
    public string IDINTERMEDIOS { get; set; }
}
