//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class VW_VLR_PRESUPUESTO
{
    public int idprod { get; set; }
    public string producto { get; set; }
    public int iditem { get; set; }
    public string item { get; set; }
    public Nullable<decimal> vlr { get; set; }
}
